// <auto-generated />
using System;
using AdminAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("AdminAPI.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Sigla")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("AdminAPI.Models.Politico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<bool>("Lider")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int?>("PartidoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PartidoId");

                    b.ToTable("Politicos");
                });

            modelBuilder.Entity("AdminAPI.Models.Processo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<int?>("PoliticoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticoId");

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("AdminAPI.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroLei")
                        .HasColumnType("longtext");

                    b.Property<int?>("PoliticoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoliticoId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("AdminAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<string>("User")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AdminAPI.Models.Politico", b =>
                {
                    b.HasOne("AdminAPI.Models.Partido", "Partido")
                        .WithMany("Politicos")
                        .HasForeignKey("PartidoId");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("AdminAPI.Models.Processo", b =>
                {
                    b.HasOne("AdminAPI.Models.Politico", "Politico")
                        .WithMany("Processos")
                        .HasForeignKey("PoliticoId");

                    b.Navigation("Politico");
                });

            modelBuilder.Entity("AdminAPI.Models.Projeto", b =>
                {
                    b.HasOne("AdminAPI.Models.Politico", "Politico")
                        .WithMany("Projetos")
                        .HasForeignKey("PoliticoId");

                    b.Navigation("Politico");
                });

            modelBuilder.Entity("AdminAPI.Models.Partido", b =>
                {
                    b.Navigation("Politicos");
                });

            modelBuilder.Entity("AdminAPI.Models.Politico", b =>
                {
                    b.Navigation("Processos");

                    b.Navigation("Projetos");
                });
#pragma warning restore 612, 618
        }
    }
}
